# Generated by Django 5.2.6 on 2025-09-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='a_deduct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wallet',
            name='actual_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
